name: Delete artifact branch when pull requests are closed
on:
  pull_request:
    types: [closed]
jobs:
  delete-branch:
    name: Delete artifact branch
    runs-on: ubuntu-latest
    steps:
      - name: Set target branch
        id: find-target
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get update && sudo apt-get install -y hub
          echo "Searching for pr branch for number $PR_NUMBER"
          echo "List all prs:"
          hub pr list -f "%I|%H|%n"
          TARGET_BRANCH_NAME=$(hub pr list -f "%I|%H|%n" | grep "$PR_NUMBER.*" | cut -d "|" -f2)
          echo "TARGET_BRANCH=$TARGET_BRANCH_NAME" >> "$GITHUB_OUTPUT"
          git switch --orphan "$TARGET_BRANCH_NAME-artifacts"
      - name: Delete artifact target branch
        id: delete-artifact-target-branch
        env:
          TARGET_BRANCH: ${{ steps.find-target.outputs.TARGET_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin :"$TARGET_BRANCH-artifacts"
      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
